!pip install yfinance pandas ta gspread gspread-dataframe -q

import yfinance as yf
import pandas as pd
import numpy as np
from ta.trend import ADXIndicator
import gspread
from gspread_dataframe import set_with_dataframe
import json
import os
import warnings
warnings.filterwarnings('ignore')

# NIFTY 500 LIST - cleaned
nifty500 = [
'3MINDIA.NS','ABB.NS','ACC.NS','AIAENG.NS','APLAPOLLO.NS','AUBANK.NS','AARTIIND.NS','AAVAS.NS','ABBOTINDIA.NS','ACE.NS',
'ABFRL.NS','ADANIENSOL.NS','ADANIENT.NS','ADANIGREEN.NS','ADANIPORTS.NS','ADANIPOWER.NS','ATGL.NS','AWL.NS','ABCAPITAL.NS','ABSLAMC.NS',
'ABREL.NS','ACMESOLAR.NS','ADVENZYMES.NS','AEGISLOG.NS','AETHER.NS','AFFLE.NS','AJANTPHARM.NS','AKZOINDIA.NS','ALEMBICLTD.NS','ALKYLAMINE.NS',
'ALLCARGO.NS','AMBER.NS','AMBUJACEM.NS','ANANDRATHI.NS','ANGELONE.NS','ANURAS.NS','APARINDS.NS','APLLTD.NS','APOLLOHOSP.NS','APOLLOTYRE.NS',
'APTUS.NS','ASAHIINDIA.NS','ASHOKLEY.NS','ASIANPAINT.NS','ASTERDM.NS','ASTRAZEN.NS','ASTRAL.NS','ATUL.NS','AUROPHARMA.NS','AVANTIFEED.NS',
'AXISBANK.NS','BAJAJ-AUTO.NS','BAJFINANCE.NS','BAJAJFINSV.NS','BAJAJHLDNG.NS','BALAMINES.NS','BALKRISIND.NS','BALRAMCHIN.NS','BANDHANBNK.NS','BANKBARODA.NS',
'BANKINDIA.NS','BATAINDIA.NS','BAYERCROP.NS','BERGEPAINT.NS','BDL.NS','BELRISE.NS','BEML.NS','BEPL.NS','BHARATFORG.NS','BHARTIARTL.NS',
'BHEL.NS','BIKAJI.NS','BIOCON.NS','BIRLACORPN.NS','BLUEJET.NS','BLUEDART.NS','BLUESTARCO.NS','BLS.NS','BOROLTD.NS','BOSCHLTD.NS',
'BPCL.NS','BRIGADE.NS','BRITANNIA.NS','BSE.NS','BSOFT.NS','CAMPUS.NS','CANBK.NS','CANFINHOME.NS','CAPLIPOINT.NS','CARBORUNIV.NS',
'CARERATING.NS','CASTROLIND.NS','CDSL.NS','CEATLTD.NS','CELLO.NS','CESC.NS','CAMS.NS','CGCL.NS','CGPOWER.NS','CHALET.NS',
'CHAMBLFERT.NS','CHEMPLASTS.NS','CHENNPETRO.NS','CHOLAHLDNG.NS','CHOLAFIN.NS','CIEINDIA.NS','CIPLA.NS','CUB.NS','COALINDIA.NS','COCHINSHIP.NS',
'COFORGE.NS','COLPAL.NS','CONCOR.NS','COROMANDEL.NS','CRAFTSMAN.NS','CREDITACC.NS','CRISIL.NS','CROMPTON.NS','CUMMINSIND.NS','CYIENT.NS',
'DLF.NS','DABUR.NS','DALBHARAT.NS','DATAPATTNS.NS','DEEPAKFERT.NS','DEEPAKNTR.NS','DELHIVERY.NS','DEVYANI.NS','DIVISLAB.NS','DIXON.NS',
'LALPATHLAB.NS','DMART.NS','DOMS.NS','DREAMFOLKS.NS','DRREDDY.NS','ECLERX.NS','EDELWEISS.NS','EICHERMOT.NS','EIDPARRY.NS','EIHOTEL.NS',
'ELECTCAST.NS','ELGIEQUIP.NS','EMAMILTD.NS','ENDURANCE.NS','ENGINERSIN.NS','EQUITASBNK.NS','ERIS.NS','ESCORTS.NS','EXIDEIND.NS','FEDERALBNK.NS',
'FACT.NS','FINEORG.NS','FINCABLES.NS','FINPIPE.NS','FIRSTCRY.NS','FIVESTAR.NS','FLUOROCHEM.NS','FORTIS.NS','FSL.NS','GAEL.NS',
'GAIL.NS','GICRE.NS','GMRAIRPORT.NS','GALAXYSURF.NS','GARFIBRES.NS','GICHSGFIN.NS','GILLETTE.NS','GLAND.NS','GLAXO.NS','GLENMARK.NS',
'GMDCLTD.NS','GODFRYPHLP.NS','GODREJAGRO.NS','GODREJCP.NS','GODREJIND.NS','GODREJPROP.NS','GRANULES.NS','GRAPHITE.NS','GRASIM.NS','GRAVITA.NS',
'GRINDWELL.NS','GRSE.NS','GSFC.NS','GSPL.NS','GUJGASLTD.NS','GULFOILLUB.NS','HAPPSTMNDS.NS','HCLTECH.NS','HDFCAMC.NS','HDFCBANK.NS',
'HDFCLIFE.NS','HEG.NS','HEIDELBERG.NS','HEROMOTOCO.NS','HINDALCO.NS','HINDCOPPER.NS','HINDPETRO.NS','HINDUNILVR.NS','HINDZINC.NS','HLEGLAS.NS',
'HONASA.NS','HONAUT.NS','HUDCO.NS','ICICIBANK.NS','ICICIGI.NS','ICICIPRULI.NS','IDBI.NS','IDFCFIRSTB.NS','IEX.NS','IIFL.NS',
'INDHOTEL.NS','INDIACEM.NS','INDIAMART.NS','INDIANB.NS','INDIGO.NS','INDIGOPNTS.NS','INDUSINDBK.NS','INDUSTOWER.NS','INFY.NS','INOXWIND.NS',
'INTELLECT.NS','IOB.NS','IOC.NS','IOLCP.NS','IPCALAB.NS','IRB.NS','IRCON.NS','IRCTC.NS','IRFC.NS','IREDA.NS',
'ITC.NS','ITI.NS','INDIGRID.NS','INDGN.NS','IGL.NS','J&KBANK.NS','JKCEMENT.NS','JBCHEPHARM.NS','JBMA.NS','JINDALSAW.NS',
'JSL.NS','JSWENERGY.NS','JSWSTEEL.NS','JUBLFOOD.NS','JUBLINGREA.NS','JUBLPHARMA.NS','JUSTDIAL.NS','JYOTHYLAB.NS','KAJARIACER.NS','KPIL.NS',
'KPRMILL.NS','KALYANKJIL.NS','KANSAINER.NS','KARURVYSYA.NS','KEC.NS','KEI.NS','KFINTECH.NS','KIRLOSBROS.NS','KIRLOSENG.NS','KOTAKBANK.NS',
'KPITTECH.NS','KNRCON.NS','KRBL.NS','KSB.NS','LTF.NS','LTTS.NS','LICI.NS','LTIM.NS','LT.NS','LATENTVIEW.NS',
'LAURUSLABS.NS','LAXMICOT.NS','LINDEINDIA.NS','LLOYDSME.NS','LEMONTREE.NS','LICHSGFIN.NS','LUPIN.NS','MMTC.NS','MOIL.NS','M&MFIN.NS',
'M&M.NS','MAHABANK.NS','MAHLOG.NS','MANAPPURAM.NS','MRF.NS','MARICO.NS','MARUTI.NS','MASTEK.NS','MATRIMONY.NS','MAXHEALTH.NS',
'MAZDOCK.NS','MEDANTA.NS','METROPOLIS.NS','MFSL.NS','MGL.NS','MIDHANI.NS','MINDACORP.NS','MOTILALOFS.NS','MPHASIS.NS','MRPL.NS',
'MUTHOOTFIN.NS','NATCOPHARM.NS','NBCC.NS','NCC.NS','NHPC.NS','NMDC.NS','NSLNISP.NS','NTPC.NS','NTPCGREEN.NS','NH.NS',
'NATIONALUM.NS','NAUKRI.NS','NAVINFLUOR.NS','NESTLEIND.NS','NETWEB.NS','NETWORK18.NS','NEWGEN.NS','NAM-INDIA.NS','NUVAMA.NS','OBEROIRLTY.NS',
'ONGC.NS','OIL.NS','OLECTRA.NS','OFSS.NS','POLICYBZR.NS','PAGEIND.NS','PATELENG.NS','PERSISTENT.NS','PETRONET.NS','PFIZER.NS',
'PHOENIXLTD.NS','PIDILITIND.NS','PIIND.NS','PNB.NS','PNBHOUSING.NS','PNCINFRA.NS','POLYCAB.NS','POLYMED.NS','POONAWALLA.NS','PFC.NS',
'POWERGRID.NS','PRAJIND.NS','PRESTIGE.NS','PRINCEPIPE.NS','PRSMJOHNSN.NS','PGHH.NS','PUNJABCHEM.NS','PVRINOX.NS','QUESS.NS','RAILTEL.NS',
'RAIN.NS','RAINBOW.NS','RAJESHEXPO.NS','RALLIS.NS','RAMCOCEM.NS','RATNAMANI.NS','RAYMOND.NS','RBLBANK.NS','RECLTD.NS','REDINGTON.NS',
'RELAXO.NS','RELIANCE.NS','RESPONIND.NS','RITES.NS','RVNL.NS','ROUTE.NS','SBFC.NS','SBICARD.NS','SBILIFE.NS','SAIL.NS',
'SAMMAANCAP.NS','SAPPHIRE.NS','SAREGAMA.NS','SCHAEFFLER.NS','SCHNEIDER.NS','SCI.NS','SFL.NS','SHOPERSTOP.NS','SHREECEM.NS','SHRIRAMFIN.NS',
'SHYAMMETL.NS','SIEMENS.NS','SIGNATURE.NS','SJVN.NS','SKFINDIA.NS','SOBHA.NS','SOLARINDS.NS','SONACOMS.NS','SONATSOFTW.NS','SOUTHBANK.NS',
'SPANDANA.NS','SPLPETRO.NS','SRF.NS','STARHEALTH.NS','SUNDRMFAST.NS','SUNPHARMA.NS','SUNTV.NS','SUPREMEIND.NS','SURYAROSNI.NS','SUZLON.NS',
'SWANENERGY.NS','SYMPHONY.NS','SYNGENE.NS','TBOTEK.NS','TMB.NS','TANLA.NS','TATACHEM.NS','TATACOMM.NS','TCS.NS','TATACONSUM.NS',
'TATAELXSI.NS','TATAINVEST.NS','TATAPOWER.NS','TATASTEEL.NS','TATATECH.NS','TTML.NS','TEJASNET.NS','TECHM.NS','TEAMLEASE.NS','THANGAMAYL.NS',
'THERMAX.NS','TIINDIA.NS','TIMKEN.NS','TITAN.NS','TORNTPHARM.NS','TORNTPOWER.NS','TRENT.NS','TRIDENT.NS','TRIVENI.NS','TRITURBINE.NS',
'TTKPRESTIG.NS','TVSMOTOR.NS','UCOBANK.NS','UNIONBANK.NS','UBL.NS','ULTRACEMCO.NS','UNOMINDA.NS','UPL.NS','USHAMART.NS','UTIAMC.NS',
'UJJIVANSFB.NS','VBL.NS','VGUARD.NS','VIPIND.NS','DBREALTY.NS','VTL.NS','VARROC.NS','VEDL.NS','VENKEYS.NS','VESUVIUS.NS',
'VIJAYA.NS','VINATIORGA.NS','IDEA.NS','VOLTAS.NS','WAAREEENER.NS','WELCORP.NS','WELSPUNLIV.NS','WESTLIFE.NS','WHIRLPOOL.NS','WIPRO.NS',
'WOCKPHARMA.NS','YESBANK.NS','ZENTEC.NS','ZENSARTECH.NS','ZFCVINDIA.NS','ZYDUSLIFE.NS','ZYDUSWELL.NS'
]

def scan_vcp(ticker):
    try:
        df = yf.download(ticker, period='6mo', interval='1d', progress=False, auto_adjust=True)
        if df.empty or len(df) < 50: return None
        if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.droplevel(1)
        h, l, c, v = df['High'].squeeze(), df['Low'].squeeze(), df['Close'].squeeze(), df['Volume'].squeeze()
        df['range'] = h - l
        df['avg_range'] = df['range'].rolling(10).mean()
        contraction = df['avg_range'].iloc[-1] < df['avg_range'].iloc[-20:-10].mean()
        df['avg_vol'] = v.rolling(50).mean()
        vol_dry = v.iloc[-10:].mean() < df['avg_vol'].iloc[-1] * 0.7
        df['sma50'] = c.rolling(50).mean()
        above_sma = c.iloc[-1] > df['sma50'].iloc[-1]
        adx = ADXIndicator(high=h, low=l, close=c, window=14)
        strong_trend = adx.adx().iloc[-1] > 25
        rating = sum([contraction, vol_dry, above_sma, strong_trend])
        if rating >= 3:
            vcp_high = h.iloc[-20:].max()
            vcp_low = l.iloc[-20:].min()
            entry = round(vcp_high * 1.01, 2)
            sl = round(vcp_low * 0.99, 2)
            risk = entry - sl
            return {'Stock': ticker.replace('.NS',''), 'Scan': f'VCP {rating}/4', 'CMP': round(c.iloc[-1],2),
                    'Entry': entry, 'SL': sl, 'T1': round(entry + risk*2,2), 'T2': round(entry + risk*3,2)}
    except: return None

results = []
for stock in nifty500:
    res = scan_vcp(stock)
    if res: results.append(res)

df_results = pd.DataFrame(results)
if not df_results.empty:
    df_results = df_results.sort_values(['Scan', 'Stock'], ascending=[False, True])
    print(df_results.to_string(index=False))

    # Save to Google Sheets using Service Account
    creds_json = os.environ.get('GOOGLE_CREDS')
    if creds_json:
        creds_dict = json.loads(creds_json)
        gc = gspread.service_account_from_dict(creds_dict)
        sh = gc.open_by_key(os.environ.get('SHEET_ID'))
        worksheet = sh.sheet1
        worksheet.clear()
        set_with_dataframe(worksheet, df_results)
        print("Saved to Google Sheets")
else:
    print("No VCP setups found today")
